# https://taskfile.dev

version: "3"

env:
  LOCALES: [] # list your included locales here, e.g. ["de", "fr"]
  TRANSLATIONS: octoprint_sidebar_macros/translations # translations folder, do not touch

tasks:
  install:
    desc: Installs the plugin into the current venv
    cmds:
      - "python3 -m pip install -e .[develop]"

  ### Build related

  build:
    desc: Builds sdist & wheel
    cmds:
      - python3 -m build --sdist --wheel

  build-sdist:
    desc: Builds sdist
    cmds:
      - python3 -m build --sdist

  build-wheel:
    desc: Builds wheel
    cmds:
      - python3 -m build --wheel

  ### Linting stuff

  lint-py:
    desc: Lint Python sources with Ruff
    cmds:
      - python3 -m ruff check .

  format-py:
    desc: Format Python sources with Ruff
    cmds:
      - python3 -m ruff format .

  format-py-check:
    desc: Check Python formatting with Ruff
    cmds:
      - python3 -m ruff format --check .

  lint-web:
    desc: Check web/docs formatting with Prettier
    cmds:
      - npx prettier --check .

  format-web:
    desc: Format web/docs files with Prettier
    cmds:
      - npx prettier --write .

  pre-commit-install:
    desc: Install pre-commit git hook scripts
    cmds:
      - python3 -m pre_commit install

  pre-commit:
    desc: Run all pre-commit hooks
    cmds:
      - python3 -m pre_commit run --all-files

  compile-less:
    desc: Compile LESS sources to CSS via pre-commit hook
    cmds:
      - python3 -m pre_commit run lessc --all-files

  ### Translation related

  babel-new:
    desc: Create a new translation for a locale
    cmds:
      - task: babel-extract
      - |
        pybabel init --input-file=translations/messages.pot --output-dir=translations --locale="{{ .CLI_ARGS }}"

  babel-extract:
    desc: Update pot file from source
    cmds:
      - pybabel extract --mapping-file=babel.cfg --output-file=translations/messages.pot --msgid-bugs-address=i18n@octoprint.org --copyright-holder="The OctoPrint Project" .

  babel-update:
    desc: Update translation files from pot file
    cmds:
      - for:
          var: LOCALES
        cmd: pybabel update --input-file=translations/messages.pot --output-dir=translations --locale={{ .ITEM }}

  babel-refresh:
    desc: Update translation files from source
    cmds:
      - task: babel-extract
      - task: babel-update

  babel-compile:
    desc: Compile translation files
    cmds:
      - pybabel compile --directory=translations

  babel-bundle:
    desc: Bundle translations
    preconditions:
      - test -d {{ .TRANSLATIONS }}
    cmds:
      - for:
          var: LOCALES
        cmd: |
          locale="{{ .ITEM }}"
          source="translations/${locale}"
          target="{{ .TRANSLATIONS }}/${locale}"

          [ ! -d "${target}" ] || rm -r "${target}"

          echo "Copying translations for locale ${locale} from ${source} to ${target}..."
          cp -r "${source}" "${target}"
